Add empty rails project

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,18 +1,36 @@
-#!/usr/bin/env sh
+#!/usr/bin/env ruby
+require "fileutils"
 
-# Run this script immediately after cloning the codebase.
-# https://github.com/thoughtbot/guides/tree/master/protocol
+# path to your application root.
+APP_ROOT = File.expand_path('..', __dir__)
 
-# Exit if any subcommand fails
-set -e
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-# Set up Ruby dependencies via Bundler
-if ! command -v bundle > /dev/null; then
-  gem install bundler --no-document --pre
-fi
+FileUtils.chdir APP_ROOT do
+  # This script is a way to set up or update your development environment automatically.
+  # This script is idempotent, so that you can run it at any time and get an expectable outcome.
+  # Add necessary setup steps to this file.
 
-bundle install
+  puts '== Installing dependencies =='
+  system! 'gem install bundler --conservative'
+  system('bundle check') || system!('bundle install')
 
-# Add bin to path if using thoughtbot dotfiles:
-# http://goo.gl/CPzari
-mkdir .git/safe
+  # Install JavaScript dependencies
+  system! 'bin/yarn'
+
+  # puts "\n== Copying sample files =="
+  # unless File.exist?('config/database.yml')
+  #   FileUtils.cp 'config/database.yml.sample', 'config/database.yml'
+  # end
+
+  puts "\n== Preparing database =="
+  system! 'bin/rails db:prepare'
+
+  puts "\n== Removing old logs and tempfiles =="
+  system! 'bin/rails log:clear tmp:clear'
+
+  puts "\n== Restarting application server =="
+  system! 'bin/rails restart'
+end
