Create fundamentals of TDD project

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,36 +1,21 @@
-#!/usr/bin/env ruby
-require "fileutils"
+#!/bin/sh
 
-# path to your application root.
-APP_ROOT = File.expand_path('..', __dir__)
+# Set up Rails app. Run this script immediately after cloning the codebase.
+# https://github.com/thoughtbot/guides/tree/master/protocol
 
-def system!(*args)
-  system(*args) || abort("\n== Command #{args} failed ==")
-end
+# Exit if any subcommand fails
+set -e
 
-FileUtils.chdir APP_ROOT do
-  # This script is a way to set up or update your development environment automatically.
-  # This script is idempotent, so that you can run it at any time and get an expectable outcome.
-  # Add necessary setup steps to this file.
+# Set up Ruby dependencies via Bundler
+gem install bundler --conservative
+bundle check || bundle install
 
-  puts '== Installing dependencies =='
-  system! 'gem install bundler --conservative'
-  system('bundle check') || system!('bundle install')
+# Set up database and add any development seed data
+bin/rake dev:prime
 
-  # Install JavaScript dependencies
-  system! 'bin/yarn'
+# Add binstubs to PATH via export PATH=".git/safe/../../bin:$PATH" in ~/.zshenv
+mkdir -p .git/safe
 
-  # puts "\n== Copying sample files =="
-  # unless File.exist?('config/database.yml')
-  #   FileUtils.cp 'config/database.yml.sample', 'config/database.yml'
-  # end
-
-  puts "\n== Preparing database =="
-  system! 'bin/rails db:prepare'
-
-  puts "\n== Removing old logs and tempfiles =="
-  system! 'bin/rails log:clear tmp:clear'
-
-  puts "\n== Restarting application server =="
-  system! 'bin/rails restart'
-end
+# Only if this isn't CI
+# if [ -z "$CI" ]; then
+# fi
